server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
